### ISSUE TITLE
Missing local downloaded images (svg) on Android

### ISSUE THREAD

**Issue by VitalyPeryatin** [qdsfdhvh/compose-imageloader#88]
Some images are lost after recompose screen (for example returning back to screen with images)
<img width="252" alt="image" src="https://user-images.githubusercontent.com/22561563/222095707-c5a58eb8-ef77-4b75-9410-423b4fcba4aa.png">

Logger doesn't show any errors: 
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/22561563/222096057-d62cc3e7-593a-45c2-8037-2320f1fab48e.png">
<img width="769" alt="image" src="https://user-images.githubusercontent.com/22561563/222096124-193d88b4-8565-4977-9b78-b488518579ec.png">

I use library such way: 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/22561563/222096408-92417e72-c98d-4f50-8e8e-61a0ad765763.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/22561563/222096539-95a56b3f-7cb5-415e-ad1c-133e1e07716e.png">

**Comment by qdsfdhvh** [comment]
mapper log has probilem and i fixed it #58. This missing image is display at the beginning and not displayed after return back? Can you try to give `Icon` or `Image` a fixed size and can it be displayed properly?

**Comment by VitalyPeryatin** [comment]
> This missing image is display at the beginning and not displayed after return back?
Yes. All images are displayed at the begining, but some images are missed after return back. Approximately every second time after returning back 1 of 5 images are missed. Probably there is a problem with asynchronous work

**Comment by VitalyPeryatin** [comment]
> Can you try to give `Icon` or `Image` a fixed size and can it be displayed properly?

If I set a fixed size for `Icon` or `Image` svg file not displayed after returning back too

**Comment by VitalyPeryatin** [comment]
I use this library in my OpenSource project [1Coin](https://github.com/1Coin-FinanceTracker/1CoinClient), so you can check behavior of icon loading yourself (if it can help you)

**Comment by qdsfdhvh** [comment]
I've read that the problem is roughly the following [here](https://github.com/qdsfdhvh/compose-imageloader/blob/master/image-loader/src/commonMain/singleton/com/seiko/imageloader/AsyncImagePainter.kt#LL162C49-L162C51), If the `Icon` not have a defiend size, it's might possible not to get a valid size here in time; I'll fix it, but maybe need one day.

**Comment by qdsfdhvh** [comment]
For svg images, `Icon` and `Image` if no `Modifier.size`, the default `SizeResolver` in [AsyncImagePainter](https://github.com/qdsfdhvh/compose-imageloader/blob/master/image-loader/src/commonMain/singleton/com/seiko/imageloader/AsyncImagePainter.kt#L161) may not fetch size.
It is recommended that  prioritize the configuration of `Modifier.size` if you can, otherwise:
```kotlin
ImageRequest { size( SizeResolver(DpSize(24.dp, 24.dp))) } 
```
PS: 24.dp  is `Icon` default size, I also set it as default in library if not fetch size.

**Comment by qdsfdhvh** [comment]
v1.2.10 Uploading in progress, try to see if it is solved

**Comment by qdsfdhvh** [comment]
There is still a problem with the default svg size in library, I will fix later.

**Comment by VitalyPeryatin** [comment]
Bug is fixed. Thank you! 

I would like to thank you. How can I donate you?)

**Comment by qdsfdhvh** [comment]
Thank you very much, I will enable GitHub Sponsor later
